apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phonebook-backend__SUFFIX__
  namespace: __NAMESPACE__
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phonebook-backend
        stage: __STAGE__
    spec:
      containers:
      - name: phonebook-backend
        image: registry:5000/__NAMESPACE__/phonebook-backend:__IMG_VERSION__
        ports:
        - containerPort: 9293
      - name: phonebook-redis
        image: registry:5000/infra/redis:3.0.7
        ports:
        - containerPort: 6379
